export default [
    {
      id: 1,
      postedOn: new Date(),
      title: "Frontend Developer",
      type: "Full time",
      location: "Remote",
      companyName: "Google",
      companyUrl: "https://google.com",
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://google.com/careers",
    },
    {
      id: 2,
      postedOn: new Date(),
      title: "Backend Developer",
      type: "Part time",
      location: "Office",
      companyName: "Yahoo",
      companyUrl: "https://yahoo.com",
      skills: ["Angular", "Node.js"],
      link: "https://yahoo.com/jobs",
    },
    {
      id: 3,
      postedOn: new Date(),
      title: "Mobile Developer",
      type: "Contract",
      location: "Remote",
      companyName: "Facebook",
      companyUrl: "https://facebook.com",
      skills: ["Flutter"],
      link: "https://facebook.com/careers",
    },
    {
      id: 4,
      postedOn: new Date(),
      title: "Data Scientist",
      type: "Full time",
      location: "New York",
      companyName: "IBM",
      companyUrl: "https://ibm.com",
      skills: ["Python", "Machine Learning", "Data Analysis"],
      link: "https://ibm.com/careers",
    },
    {
      id: 5,
      postedOn: new Date(),
      title: "DevOps Engineer",
      type: "Full time",
      location: "San Francisco",
      companyName: "Amazon",
      companyUrl: "https://amazon.com",
      skills: ["AWS", "Docker", "CI/CD"],
      link: "https://amazon.com/careers",
    },
    {
      id: 6,
      postedOn: new Date(),
      title: "UI/UX Designer",
      type: "Contract",
      location: "Remote",
      companyName: "Spotify",
      companyUrl: "https://spotify.com",
      skills: ["Sketch", "Figma", "Prototyping"],
      link: "https://spotify.com/careers",
    },
    {
      id: 7,
      postedOn: new Date(),
      title: "Product Manager",
      type: "Full time",
      location: "Remote",
      companyName: "Apple",
      companyUrl: "https://apple.com",
      skills: ["Product Management", "Agile", "Communication"],
      link: "https://apple.com/careers",
    },
    {
      id: 8,
      postedOn: new Date(),
      title: "Software Engineer",
      type: "Part time",
      location: "Remote",
      companyName: "Netflix",
      companyUrl: "https://netflix.com",
      skills: ["Java", "Spring", "Microservices"],
      link: "https://netflix.com/careers",
    },
    {
      id: 9,
      postedOn: new Date(),
      title: "System Administrator",
      type: "Full time",
      location: "Boston",
      companyName: "Microsoft",
      companyUrl: "https://microsoft.com",
      skills: ["Linux", "Bash", "Networking"],
      link: "https://microsoft.com/careers",
    },
    {
      id: 10,
      postedOn: new Date(),
      title: "Cloud Architect",
      type: "Full time",
      location: "Seattle",
      companyName: "Google Cloud",
      companyUrl: "https://cloud.google.com",
      skills: ["GCP", "Cloud Design", "Kubernetes"],
      link: "https://cloud.google.com/careers",
    },
  ];
  